.changeset/cuddly-comics-brush.md, examples/framesjs-starter/app/debug/page.tsx
- Updates the `submitOption` method to construct the `untrustedMessage` data's `url` field using the frame's original url instead of the post url.
=> fix(debug): construct untrusted message data using original frame url

examples/framesjs-starter/README.md
The current link doesn't bring me to the `frames-dev` channel.
=> Link to Frames Devs Channel

.changeset/eleven-bobcats-explode.md, examples/framesjs-starter/app/debug/components/frame-render.tsx, examples/framesjs-starter/app/debug/lib/farcaster.ts, examples/framesjs-starter/app/debug/page.tsx
Fixes types and frame action message creation to not include inputText if inputText was not requested by the frame.
=> fix(core+debug): inputText can be undefined in frame action message

.changeset/cold-pumpkins-learn.md, docs/pages/reference/js/getAddressForFid.mdx, docs/pages/reference/js/types.mdx, packages/frames.js/src/getAddressForFid.test.ts, packages/frames.js/src/getAddressForFid.ts, packages/frames.js/src/types.ts, packages/frames.js/src/validateFrameMessage.ts
- Adds an optional second arg for `validateFrameMessage` to specify hub url, which falls back to nemes by default.
- Adds the same options to getAddressForFid and removes hubClient arg
=> fix: hubHttpUrl in options arg for getAddressForFid and validateFrameMessage

.changeset/brown-nails-search.md, .changeset/cold-pumpkins-learn.md, docs/pages/reference/js/getAddressForFid.mdx, docs/pages/reference/js/types.mdx, examples/framesjs-starter/app/debug/components/create-signer.tsx, examples/framesjs-starter/app/debug/constants.ts, examples/framesjs-starter/app/debug/hooks/use-farcaster-identity.tsx, examples/framesjs-starter/app/debug/hub/v1/validateMessage/route.ts, examples/framesjs-starter/app/debug/page.tsx, examples/framesjs-starter/app/debug/types/farcaster-user.ts, examples/framesjs-starter/app/page.tsx, packages/frames.js/src/getAddressForFid.test.ts, packages/frames.js/src/getAddressForFid.ts, packages/frames.js/src/next/server.tsx, packages/frames.js/src/types.ts, packages/frames.js/src/validateFrameMessage.ts, yarn.lock
- Adds an impersonation option to the debugger that allows the user to specify an FID to impersonate as an alternative to creating a new onchain signer
- Adds a mock implementation of a hub's HTTP REST API's `validateMessage` endpoint which doesn't verify signatures
Depends on #13
=> feat: signerless debugger 

examples/framesjs-starter/app/debug/frame-action/route.ts, examples/framesjs-starter/app/debug/page.tsx
Update debugger to pass the current frame's post url to the debugger's `frame-action` endpoint as it is not present in the action payload.
=> fix(debug): pass postUrl to frame-action endpoint

packages/frames.js/package.json
Currently, `import { Frame, getFrameFlattened } from "frames.js"` will include `farcaster/core` in final bundled file, thus, the file size is not optimized enough.
This PR proposes that we can import helper function individually so improve a bit on tree-shaking.
We can checkout the reproduce demo here: https://github.com/Leechael/framesjs-fix-demo
Result:
```
❯ l dist    
Permissions Size User     Date Modified Name
.rw-rw-r--   152 leechael  5 Feb 16:26  before.d.ts
.rw-rw-r--  5.9M leechael  5 Feb 16:26  before.js
.rw-rw-r--   161 leechael  5 Feb 16:26  getFrameFlattened.d.ts
.rw-rw-r--  1.5k leechael  5 Feb 16:26  getFrameFlattened.js
.rw-rw-r--  792k leechael  5 Feb 16:26  metafile-cjs.json
.rw-rw-r--   203 leechael  5 Feb 16:26  validateFrameMessage.d.ts
.rw-rw-r--  5.9M leechael  5 …
```
=> Improved: make helper functions can import individually & improve a bit on tree-shaking

.changeset/honest-apes-work.md, .changeset/slimy-wombats-hunt.md, docs/pages/index.mdx, docs/pages/reference/js/getAddressForFid.mdx, docs/pages/reference/js/getFrameMessage.mdx, docs/pages/reference/js/getUserDataForFid.mdx, docs/pages/reference/js/types.mdx, docs/vocs.config.tsx, examples/framesjs-starter/app/debug/hub/[...hubPath]/route.ts, examples/framesjs-starter/app/generate-image.tsx, examples/framesjs-starter/app/page.tsx, examples/framesjs-starter/package.json, examples/utils-starter/package.json, packages/frames.js/package.json, packages/frames.js/src/getFrameMessage.ts, packages/frames.js/src/getUserDataForFid.test.ts, packages/frames.js/src/getUserDataForFid.ts, packages/frames.js/src/index.ts, packages/frames.js/src/next/server.tsx, packages/frames.js/src/types.ts
- Add `getFrameMessage`, which parse frame action payloads and optionally fetches additional context from hubs.
- Forward unmocked hub requests to an actual hub.
Closes #21
=> feat: getFrameMessage

.changeset/selfish-avocados-burn.md, .changeset/seven-teachers-bake.md, .changeset/unlucky-pumas-design.md, docs/pages/reference/js/types.mdx, examples/framesjs-starter/CHANGELOG.md, examples/framesjs-starter/app/examples/user-data/generate-image.tsx, examples/framesjs-starter/app/examples/user-data/page.tsx, examples/framesjs-starter/app/page.tsx, examples/framesjs-starter/package.json, examples/utils-starter/CHANGELOG.md, examples/utils-starter/package.json, packages/frames.js/CHANGELOG.md, packages/frames.js/package.json, packages/frames.js/src/getAddressForFid.ts, packages/frames.js/src/getFrameMessage.ts, packages/frames.js/src/getUserDataForFid.ts, packages/frames.js/src/next/server.tsx, packages/frames.js/src/types.ts, packages/frames.js/src/validateFrameMessage.ts, yarn.lock
- Exposes `RequestInit` of fetch requests made to Hub HTTP endpoints. Useful for including API keys when making authenticated requests to hub providers such as Neynar.
Usage:
```ts
const message = await getFrameMessage(frameActionPayload, {
hubHttpUrl: 'https://api.neynar.com:2281',
hubRequestOptions: {
headers: {
api_key: process.env.NEYNAR_API_KEY
}
}
})
```
- Throws more useful error when specifying an invalid hub url in nextjs
=> feat: http request options

.changeset/proud-books-turn.md, .changeset/wicked-pianos-wait.md, docs/pages/reference/js/types.mdx, examples/framesjs-starter/app/debug/frame-action/route.ts, examples/framesjs-starter/app/debug/hub/[...hubPath]/route.ts, examples/framesjs-starter/app/examples/user-data/page.tsx, examples/framesjs-starter/app/page.tsx, packages/frames.js/src/getAddressForFid.ts, packages/frames.js/src/getFrameMessage.ts, packages/frames.js/src/getUserDataForFid.ts, packages/frames.js/src/types.ts, packages/frames.js/src/validateFrameMessage.ts
- Use use neynar hubs as fallback with public API key
- Clean up options defaults
- Fix `getFrameMessage` return type
=> fix: use neynar hubs as fallback, clean up options defaults

.changeset/long-cows-matter.md, packages/frames.js/src/getFrameHtml.ts
The `frames.js 0.4.2` version includes support to `fc:frame:image:aspect_ratio` is in `Frame` type definition, but the prop is missing in `getFrameHtmlHead()` I've just added the meta tag creation if is in `frame` object.
=> chore: add meta frame.imageAspectRatio to getFrameHtmlHead fn in getFrameHtml.ts

examples/framesjs-starter/README.md
This PR updates the starter script README to reflect the need for running `yarn` in the root directory when running `framesjs-starter` from the context of the monorepo.
- Ensures `frames.js` is built so that the example can be ran
=> fix: update starter script steps

.changeset/stale-numbers-sit.md, examples/framesjs-starter/app/debug/components/frame-render.tsx
- Resets input text when frame renderer's frame changes
- Fixes waiting state styling on buttons which weren't having an effect due to ordering
=> fix(debugger): reset input, waiting state styling

examples/framesjs-starter/app/debug/page.tsx, examples/framesjs-starter/app/examples/mint-button/frames/route.ts, examples/framesjs-starter/app/examples/mint-button/page.tsx, examples/framesjs-starter/app/page.tsx
Removes the mint button from the frames.js starter page because it breaks rendering in warpcast (see thread: https://warpcast.com/stephancill/0xbed7a00f)
=> fix: remove mint action from demo as it breaks warpcast image rendering

.changeset/mighty-years-sleep.md, examples/framesjs-starter/app/debug/components/frame-render.tsx, packages/frames.js/src/validateFrame.ts
Adds validation for data URI length
=> feat: add validation for image data uri length

docs/pages/index.mdx, docs/vocs.config.tsx
- linking to a specific doc page is broken atm. The fix renders it into the page body since vocs abstractions don't support rendering into head
=> Fix: dont show frame on non home routes

.changeset/dry-socks-decide.md, package.json, packages/frames.js/jest.config.js, packages/frames.js/src/farcaster/generated/message.ts, packages/frames.js/src/getAddressForFid.test.ts, packages/frames.js/src/getAddressForFid.ts, packages/frames.js/src/getAddressesForFid.test.ts, packages/frames.js/src/getAddressesForFid.ts, packages/frames.js/src/getUserDataForFid.test.ts, packages/frames.js/src/getUserDataForFid.ts, packages/frames.js/src/utils.ts
This PR fixes parsing messages from JSON to protobuf representation. And handles eth addresses properly.
=> fix: correctly parse protobuf messages and return eth addresses as string

.changeset/dry-socks-decide.md, .changeset/fluffy-bottles-matter.md, .changeset/friendly-panthers-fly.md, packages/debugger/README.md, packages/frames.js/CHANGELOG.md, packages/frames.js/package.json, packages/frames.js/src/next/server.tsx
This is an alternative for #121 which doesn't require an extra param to be passed to the exported POST request and uses next.js headers to derive that info instead.
Fixes https://linear.app/modprotocol/issue/FRA-49/issues-with-docker
Closes #121 
h/t @cryptods8 for their gist which details the solution: https://gist.github.com/cryptods8/8fbfb9d5da246bc65c1292212c476ae3
=> fix: proxy SSL version error

examples/framesjs-starter/scripts/dev-script.js
When running "yarn dev" with the latest version of the starter there was a bad substitution error because of the way in which the NEXT_PUBLIC_HOST was passed to the "dev-script.js" file.
I changed it to have the correct substitution.
=> Fix NEXT_PUBLIC_HOST env variable setup

.changeset/nervous-wolves-flash.md, packages/frames.js/src/render/use-frame.tsx
Fixes an issue where url params were not being passed to the frame fetch proxy correctly.
https://warpcast.com/ds8/0x6b50c49e
=> fix: render fetch url params

.changeset/plenty-weeks-work.md, examples/framesjs-starter/app/debug.ts
Mock hub URL should only be available in development to prevent use in production.
=> fix: mock hub only dev

.changeset/lemon-frogs-cover.md, packages/frames.js/src/render/frame-ui.tsx
Fixes a bug where the frame UI's input would not clear after submitting a frame action by correctly coupling the input text value to the input field.
Fixes #169
=> fix: frame UI clear input

.changeset/soft-chairs-return.md, packages/frames.js/src/getFrame.ts
Fixes an issue where `of:button:N` would not be correctly parsed due to a hard-coded index that hadn't been updated for parsing `fc:frame:button:N`
=> fix: open frames button index parsing

examples/framesjs-starter/app/examples/new-api/page.tsx, examples/framesjs-starter/pages/page-router/index.tsx, packages/next/README.md, packages/next/src/fetchMetaData.test.ts, packages/next/src/fetchMetaData.ts, packages/next/src/index.test.ts, packages/next/src/index.ts, packages/next/src/pages-router.tsx
This PR changes `fetchMetaData` and `metaDataToMetaTags` function names so they are compatible with remix adapter
=> chore: rename fetchMetadata function

packages/frames.js/src/core/middleware/openframes.test.ts, packages/frames.js/src/core/middleware/openframes.ts
Adds type inferencing support to openframes by separating different client protocols into their own middleware.
=> fix: openframes type inference

examples/framesjs-starter/app/examples/new-api-mint-button/frames/route.tsx, examples/framesjs-starter/app/examples/new-api-multi-page/frames/route.tsx, examples/framesjs-starter/app/examples/new-api-transaction/frames/route.tsx, examples/framesjs-starter/app/examples/new-api/frames/frames.ts
This PR replaces destruture with `ctx` in examples and removes unsupported exports.
=> chore: use ctx in examples

examples/framesjs-starter/app/examples/new-api-slow-request/README.md, examples/framesjs-starter/app/examples/new-api-slow-request/frames/route.tsx, examples/framesjs-starter/app/examples/new-api-slow-request/page.tsx, examples/framesjs-starter/app/examples/new-api-slow-request/slow-fetch/route.ts, examples/framesjs-starter/app/examples/new-api-slow-request/slow-fetch/types.ts
This PR adds slow request example using new api. It depends on #196 since it needs the `target` prop on `Button`
=> feat: new slow request api example

.changeset/honest-nails-hunt.md, packages/frames.js/src/next/fetchMetadata.test.ts
`fetchMetadata` now returns an empty object and logs a warning on failed response
=> fix: fetchMetadata tests

docs/pages/guides/create-frame.mdx, docs/pages/guides/multiple-frames.mdx, docs/pages/index.mdx, docs/pages/reference/core/createFrames.mdx, docs/pages/reference/core/express/index.mdx, docs/pages/reference/core/hono/index.mdx, docs/pages/reference/core/next/index.mdx, docs/pages/reference/core/redirect.mdx, docs/pages/reference/core/remix/index.mdx
- updates docs with eslint ignoring jsx rules
=> fix: jsx lint in docs examples

.changeset/spotty-colts-provide.md, packages/frames.js/src/next/fetchMetadata.ts
Fixes initial frame not updating when `fetchMetadata` is used in `generateMetadata` due to caching rules.
=> fix: nextjs fetchMetadata cache issue

.changeset/three-pumas-walk.md, packages/frames.js/src/core/components.ts
Adds missing `UrlObject` type to `post_url` of `TxButtonProps`
=> fix: tx button post_url UrlObject type

.changeset/modern-coats-complain.md, packages/frames.js/package.json
This PR fixes a resolution issue when using `node10` typescript resolution and the imported path points to barrel file (`index.ts`). 
Following import
```ts
import { createFrames } from 'frames.js/hono';
```
Has been resolved to `frames.js/hono.d.ts` which doesn't exist. 
After the fix it first tries `frames.js/hono.d.ts` and if not found then it tries `frames.js/hono/index.d.ts`.
=> fix: allow node10 resolution to find types in barrel files

.changeset/fifty-rice-speak.md, packages/debugger/app/components/frame-debugger.tsx
Cleans up styling for debugger frame history stack
=> fix: debugger history styling

.changeset/long-bees-obey.md, packages/frames.js/src/getFrame.ts
Always validate image URL length in `getFrame`, not only when it's a data URL
=> fix: debugger image url length validation

.changeset/clean-games-brush.md, packages/frames.js/src/getFrame.test.ts, packages/frames.js/src/getFrame.ts, packages/frames.js/src/getFrameFlattened.test.ts, packages/frames.js/src/getFrameFlattened.ts, packages/frames.js/src/getFrameHtml.ts, packages/frames.js/src/types.ts
- prints the full set of `of` tags when an `accepts` value is set
- fixes `getFrame` to handle deduplication correctly
=> feat: open frames full tags

.github/workflows/github-actions.yml, jest.config.js, package.json, packages/frames.js/package.json, packages/frames.js/src/next/getCurrentUrl.test.ts, yarn.lock
This PR adds github actions to lint, typecheck and test code.
=> build: lint, typecheck and test code

.changeset/five-mangos-try.md, packages/frames.js/package.json
Removes the `rimraf` command in the frames.js build step which breaks parallel builds
=> fix: @frames/render turbo build

.changeset/ten-beans-compete.md, examples/framesjs-starter/app/examples/new-api-multi-page/frames/frames.ts, examples/framesjs-starter/app/examples/new-api-multi-page/frames/route.tsx, examples/framesjs-starter/app/examples/new-api-multi-page/frames/route1/route.tsx, examples/framesjs-starter/app/examples/new-api-multi-page/frames/route2/route.tsx
Updates multi-page example to use multiple routes
=> feat: updated multi-page example

.changeset/yellow-zoos-promise.md, examples/framesjs-starter/app/examples/new-api-custom-middleware/frames/frames.ts, examples/framesjs-starter/app/examples/new-api-custom-middleware/frames/route.tsx, examples/framesjs-starter/app/examples/new-api-custom-middleware/page.tsx
Adds custom middleware example which includes instructions on how to maintain type safety. The example does a request to fetch the eth price and adds it to the context.
Conflicts with the example from #232
=> feat: custom middleware example

.changeset/new-moose-talk.md, packages/frames.js/src/next/getCurrentUrl.ts
Allow the user to override VERCEL_URL with APP_URL in the next.js package's `getCurrentUrl` function
=> fix: getCurrentUrl env priorities

.changeset/warm-pandas-laugh.md, packages/frames.js/package.json, packages/frames.js/src/core/types.ts, packages/frames.js/src/getAddressForFid.ts, packages/frames.js/src/getAddressesForFid.ts, packages/frames.js/src/getFrameMessage.ts, packages/frames.js/src/hono/index.ts, packages/frames.js/src/middleware/__snapshots__/renderResponse.test.tsx.snap, packages/frames.js/src/middleware/farcaster.ts, packages/frames.js/src/middleware/farcasterHubContext.ts, packages/frames.js/src/middleware/framesjsMiddleware.ts, packages/frames.js/src/middleware/openframes.ts, packages/frames.js/src/middleware/renderResponse.ts, packages/frames.js/src/middleware/stateMiddleware.ts, packages/frames.js/src/next/fetchMetadata.ts, packages/frames.js/src/next/index.ts, packages/frames.js/src/next/pages-router.tsx, packages/frames.js/src/next/server.tsx, packages/frames.js/src/next/types.ts, packages/frames.js/src/remix/fetchMetadata.ts, packages/frames.js/src/remix/index.ts, packages/frames.js/src/types.ts, packages/frames.js/src/utils.ts, packages/frames.js/src/validateFrameMessage.ts, packages/frames.js/tsup.config.ts, packages/render/package.json, packages/render/tsup.config.ts
This PR fixes tree shaking of our bundle.
=> chore: changeset

.changeset/heavy-nails-love.md, docs/pages/guides/deployment.mdx, docs/pages/index.mdx, docs/pages/reference/core/cloudflare-workers/index.mdx, docs/vocs.config.tsx, packages/frames.js/package.json, packages/frames.js/src/cloudflare-workers/index.test.tsx, packages/frames.js/src/cloudflare-workers/index.ts, packages/frames.js/tsup.config.ts
This PR introduces new adapter for cloudflare workers and docs
=> docs: add cloudflare adapter docs and guide

.changeset/eight-hounds-remember.md, .github/workflows/github-actions.yml, package.json, packages/frames.js/package.json, packages/frames.js/src/cloudflare-workers/index.test.tsx, packages/frames.js/src/cloudflare-workers/index.ts, packages/frames.js/src/cloudflare-workers/test.types.tsx, packages/frames.js/src/core/createFrames.ts, packages/frames.js/src/core/test.types.tsx, packages/frames.js/src/core/types.ts, packages/frames.js/src/express/index.test.tsx, packages/frames.js/src/express/test.types.tsx, packages/frames.js/src/hono/index.test.tsx, packages/frames.js/src/hono/test.types.tsx, packages/frames.js/src/next/index.test.ts, packages/frames.js/src/next/test.types.tsx, packages/frames.js/src/remix/index.test.ts, packages/frames.js/src/remix/test.types.tsx, packages/frames.js/tsup.config.ts, turbo.json
This PR fixes how `createFrames()` function is defined. Now it takes first generic parameter as State. 
PR also adds type tests so we can at least be sure that the API works fine on type level.
=> fix: allow to explicitly set state using generics

.changeset/small-clouds-divide.md, docs/pages/guides/create-frame.mdx, docs/pages/index.mdx, packages/frames.js/README.md
=> fix: update quickstart code and fix baseUrl

.changeset/four-cheetahs-tease.md, docs/pages/middleware/farcasterHubContext.mdx
Add usage instructions and link to return types of `farcasterHubContext` middleware
=> docs: farcasterHubContext middleware usage instructions

.changeset/rich-needles-move.md, packages/render/src/frame-ui.tsx
Fixes an issue where the image loading state blur would only last until the frame has finished loading, but should last until the frame and the frame's image has finished loading.
=> fix: render image loading state

.changeset/orange-owls-agree.md, templates/cloudflare-worker/package.json, templates/express/package.json, templates/hono/package.json, templates/next-starter-with-examples/package.json, templates/next-utils-starter/package.json, templates/next/package.json, templates/remix/package.json
This PR fixes invalid dependency in `next` template and also upgrades the rest.
Closes #264
=> fix: use correct version of debugger in templates and also upgrade valid ones

.changeset/curly-badgers-drum.md, .changeset/fast-wasps-yawn.md, docs/pages/guides/state-management.mdx, docs/vocs.config.tsx, examples/framesjs-starter/app/frames/frames.ts
Adds state management docs and adds explicit state type to starter demo
=> docs: state management

.changeset/curly-queens-thank.md, .changeset/early-turkeys-impress.md, packages/debugger/app/page.tsx, packages/render/src/frame-ui.tsx, packages/render/src/use-frame.tsx
This PR fixes:
- issue when image loading was not correctly detected on image change
- issue when debugger did not open default URL on initial load
This PR also removes unnecessary url input state, etc.
=> fix: debugger initial frame load + frame ui image loading state on change

.changeset/modern-dolphins-float.md, .changeset/real-socks-appear.md, .changeset/thirty-islands-begin.md, docs/pages/reference/core/error.mdx, docs/vocs.config.tsx, examples/framesjs-starter/app/examples/new-api-error/frames/frames.ts, examples/framesjs-starter/app/examples/new-api-error/frames/route.tsx, examples/framesjs-starter/app/examples/new-api-error/page.tsx, examples/framesjs-starter/app/examples/page.tsx, packages/debugger/app/components/frame-debugger.tsx, packages/frames.js/src/core/error.ts, packages/frames.js/src/core/errors.ts, packages/frames.js/src/core/index.ts, packages/frames.js/src/middleware/renderResponse.test.tsx, packages/frames.js/src/middleware/renderResponse.ts, packages/render/src/errors.ts, packages/render/src/frame-ui.tsx, packages/render/src/next/POST.tsx, packages/render/src/types.ts, packages/render/src/use-frame.tsx
Adds support for [application errors](https://warpcast.notion.site/Frames-Errors-ddc965b097d44d9ea03ddf98498597c6)
=> feat: application error support

.changeset/brown-walls-thank.md, .changeset/tasty-panthers-protect.md, docs/pages/guides/cast-actions.mdx, docs/vocs.config.tsx, examples/framesjs-starter/app/examples/new-api-cast-actions/frames/frames.ts, examples/framesjs-starter/app/examples/new-api-cast-actions/frames/route.tsx, examples/framesjs-starter/app/examples/new-api-cast-actions/page.tsx, examples/framesjs-starter/app/examples/new-api-cast-actions/utils.ts, packages/frames.js/src/core/types.ts
Adds basic support for v1 cast actions by allowing arbitrary responses to be returned by frames handlers.
=> feat: cast actions support

.changeset/fast-lemons-hug.md, packages/frames.js/src/getFrameHtml.test.ts, packages/frames.js/src/getFrameHtml.ts, packages/frames.js/src/utils.ts
This PR properly escapes user provided HTML attribute values. This for example fixes an issue when state value contains double quotes or single quotes, etc. All proper HTML parsers should be able to decode the values properly.
https://linear.app/modprotocol/issue/FRA-176/bug-report-with-deserializing-state
=> fix: escape user provided HTML attribute values

.changeset/clean-dragons-doubt.md, docs/pages/reference/core/next/index.mdx
In the Next.js App Router integration reference, the data awaited from `fetchMetadata` in the `generateMetadata()` function is not put under the `other` attribute, causing errors when rendering the frame. Fixed by following the format found in the Quickstart guide.
=> fix: next.js generateMetadata example code

.changeset/sweet-carrots-cross.md, templates/cloudflare-worker/package.json
This PR fixes invalid `start` command in cloudflare worker template
=> fix: cloudflare worker template start command

.changeset/fast-flies-help.md, packages/debugger/app/components/create-signer.tsx, packages/debugger/package.json, yarn.lock
This PR locks `next` version used in `debugger` because `14.2.x` versions are broken and cause debugger to fail completely.
=> fix: lock next version, move react do production dependencies

.changeset/rude-snakes-act.md, packages/frames.js/src/middleware/images-worker/next/index.tsx
Updates the default font size in the images worker default container styling to match default inline image rendering
=> fix: update images worker default container styling

.changeset/config.json
Adds experimental changeset config option to always bump versions in dependents of changed package.
=> fix: always bump dependents

.changeset/wet-files-wash.md, packages/render/src/farcaster/frames.tsx
Fix a bug in `@frames.js/render` where state was not included in untrusted data.
=> fix: include state in untrusted data

.changeset/happy-trainers-film.md, packages/debugger/app/page.tsx
This PR adds an option to override default debugger URL to something else than `NEXT_PUBLIC_HOST`. 
To override the URL, set up the `NEXT_PUBLIC_DEBUGGER_DEFAULT_URL` to full url. In our case `https://framesjs.org` so hosted debugger will point to functional frame.
=> feat: allow to override default debugger url

.changeset/tame-eels-drop.md, packages/debugger/package.json, packages/render/package.json
This PR locks `neverthrow` version to `6.1.0` because `6.2.0` is missing `dist` folder. The package is subdependency of `@farcaster/core`.
See https://github.com/supermacro/neverthrow/issues/532
=> fix: lock neverthrow package version until it is fixed

.changeset/modern-steaks-reflect.md, packages/frames.js/src/middleware/stateMiddleware.test.ts, packages/frames.js/src/middleware/stateMiddleware.ts
Set previous frame state in frame response if it is set in request but is not returned in frame definition return value.
=> fix: persists unmodified frame state between frames

packages/debugger/package.json, packages/render/package.json
Reverts framesjs/frames.js#329 because the issue was resolved upstream. https://github.com/supermacro/neverthrow/issues/532
=> Revert "fix: lock neverthrow package version until it is fixed"

.changeset/blue-pigs-deliver.md, packages/render/src/types.ts, packages/render/src/use-frame.tsx
Excludes `address` from frame context in post button handler
=> fix: exclude `address` from frame context in post button handler

.changeset/pink-rings-fetch.md, docs/package.json, yarn.lock
This PR fixes docs dependencies to be `nohoist` since there is a conflict in packages causing dev client side js to be broken.
=> fix: do not hoist docs dependencies

.changeset/pretty-jobs-move.md, .changeset/tall-beans-hunt.md, packages/frames.js/src/middleware/images-worker/next/createImagesWorker.test.tsx, packages/frames.js/src/middleware/images-worker/next/index.tsx
Allow the user to specify fonts in image options without specifying dimensions.
=> fix: image worker options

.changeset/hungry-pears-yell.md, templates/next-starter-with-examples/package.json, templates/next-utils-starter/package.json, templates/next/package.json
This PR locks next version in templates to prevent failures causes by next 14.2.x
=> fix: lock next version in templates

.changeset/nine-hats-kneel.md, packages/debugger/app/components/frame-debugger.tsx, packages/render/src/frame-ui.tsx
Adds an option which allows rendering a frame which may not perfectly conform to the frames spec - useful for applications like the debugger.
=> feat: `allowPartialFrame` option for FrameUI

.changeset/swift-rivers-march.md, packages/debugger/.env.sample, packages/debugger/app/hooks/use-farcaster-identity.tsx
Delegate signer metadata signatures to hosted debugger by default to allow local use of real signers without needing to set a `FARCASTER_DEVELOPER_MNEMONIC`
Depends on #350
=> fix: debugger delegated metadata signer

.changeset/pretty-beds-enjoy.md, packages/debugger/app/frames/route.ts
Fix regression where specification search param was removed from the debugger proxy
=> fix: debugger specification search param

.changeset/hip-singers-mate.md, packages/create-frames/bin.js
This PR fixes version reported when using `create-frames --version`.
=> fix(create-frames): properly parse package version for CLI command

.changeset/chilled-days-work.md, .changeset/gentle-sloths-complain.md, packages/debugger/app/actions/use-action.tsx, packages/debugger/app/components/action-debugger.tsx, packages/debugger/app/components/frame-debugger.tsx, packages/debugger/tailwind.config.ts, packages/render/src/errors.ts, packages/render/src/frame-ui.tsx, packages/render/src/types.ts, packages/render/src/use-frame.tsx
This PR fixes error message in frame preview.
=> fix(debugger): correctly render frame error messages

.changeset/eleven-moles-camp.md, .github/workflows/github-actions.yml, docs/pages/guides/state-management.mdx, docs/pages/reference/core/createFrames.mdx, packages/frames.js/src/core/createFrames.ts, packages/frames.js/src/core/types.ts, packages/frames.js/src/lib/crypto.ts, packages/frames.js/src/middleware/images-worker/index.ts, packages/frames.js/src/middleware/images-worker/next/createImagesWorker.test.tsx, packages/frames.js/src/middleware/images-worker/next/index.tsx, packages/frames.js/src/middleware/renderResponse.test.tsx, packages/frames.js/src/middleware/renderResponse.ts, packages/frames.js/src/middleware/stateMiddleware.test.ts, packages/frames.js/src/middleware/stateMiddleware.ts, packages/frames.js/tsup.config.ts, templates/next-starter-with-examples/app/examples/new-api-state-signing/frames/frames.ts, templates/next-starter-with-examples/app/examples/new-api-state-signing/frames/route.tsx, templates/next-starter-with-examples/app/examples/new-api-state-signing/page.tsx, templates/next-starter-with-examples/app/examples/page.tsx
This PR adds `stateSigningSecret` option to `createFrames` that can be used to sign `state`.
=> feat: state signing

.changeset/purple-laws-unite.md, packages/debugger/app/components/frame-debugger.tsx, packages/frames.js/src/getFrame.test.ts, packages/frames.js/src/getFrame.ts, packages/frames.js/src/getFrameFlattened.ts, packages/frames.js/src/parseFramesWithReports.ts
This PR adds `frames.js:version` meta tag parsing to parsers and shows that in debugger.
=> feat(debugger): detect frames.js version

.changeset/selfish-bees-sparkle.md, docs/pages/guides/create-frame.mdx, docs/pages/guides/multiple-frames.mdx, docs/pages/index.mdx, docs/pages/troubleshooting.mdx
Workaround for `$` escaping issue in docs. Open issue in https://github.com/wevm/vocs/issues/164
=> fix: $ escaping in docs

.changeset/dry-cameras-cover.md, packages/frames.js/src/core/utils.test.ts, packages/frames.js/src/core/utils.ts
This PR fixes how button target url is generated if `pathname` is no provided. Closes #377.
=> fix(frames.js): correctly generate button target url if pathname is missing

.changeset/five-pants-speak.md, packages/render/package.json, packages/render/src/next/GET.tsx, packages/render/src/next/POST.tsx, packages/render/src/next/route-handlers.ts
This PR exportes next router handlers from `@frames.js/render` in isolated file as well. This is useful for only server side reexport where we don't need `react` or `next` at all.
=> feat(render): export next route handlers in isolated file

.changeset/famous-fans-poke.md, packages/debugger/package.json, packages/eslint-config/package.json, packages/frames.js/package.json, packages/render/package.json, templates/cloudflare-worker/package.json, templates/express/package.json, templates/hono/package.json, templates/next-starter-with-examples/package.json, templates/next-starter-with-examples/tsconfig.json, templates/next-utils-starter/package.json, templates/next-utils-starter/tsconfig.json, templates/next/package.json, templates/remix/package.json, yarn.lock
This PR upgrades typescript in templates to get rid of potential type inferrence errors `ts2742`.
Also it removes `declaration` and `declarationMap` properties from `tsconfig.json` which causes the error in combination with `typescript@5.3.3` (see #352).
=> fix: upgrade typescript to get rid of inference errors

.changeset/clever-bikes-pump.md, packages/frames.js/src/frame-parsers/farcaster.test.ts, packages/frames.js/src/frame-parsers/farcaster.ts, packages/frames.js/src/frame-parsers/open-frames.test.ts, packages/frames.js/src/frame-parsers/open-frames.ts, packages/frames.js/src/getFrame.test.ts
Replaces warning and parsing failure when `og:image` fallback is missing with warning
Fixes #387
=> feat: warn if og tag is missing

.changeset/healthy-dingos-crash.md, docs/pages/reference/core/next-pages-router/index.mdx, docs/pages/reference/core/next/index.mdx, packages/frames.js/src/next/fetchMetadata.ts, packages/frames.js/src/next/pages-router/client.tsx, templates/next-starter-with-examples/pages/examples/pages-router/index.tsx, templates/next/app/page.tsx
This PR fixes examples and docs where `process.env.VERCEL` is directly used to create an URL.
=> fix: properly format url based on VERCEL_URL

docs/pages/guides/apps/display-frames.mdx
Currently, there is nothing that notes that `hasSigner` will stop the running of `onSignerlessFramePress`. It is misleading to have the documentation show `hasSigner =  true` and show `onSignerlessFramePress`, when one of these overrides the other
The following changes to the guide better explain this intereaction
=> Update display-frames.mdx to better explain onSignerlessFramePress

templates/next-starter-with-examples/.env.sample, templates/next-starter-with-examples/app/debug.ts
currently if you copy the `.env.sample` file, it will set the debugger url to "" which will then break your frame
=> fix: when no debugger url specified

.changeset/bright-spies-rush.md, packages/frames.js/src/core/createFrames.test.ts, packages/frames.js/src/core/transaction.ts, packages/frames.js/src/core/utils.test.ts, packages/frames.js/src/core/utils.ts, packages/frames.js/src/middleware/framesjsMiddleware.test.ts, packages/frames.js/src/middleware/framesjsMiddleware.ts, packages/frames.js/src/middleware/renderResponse.test.tsx, packages/frames.js/src/middleware/renderResponse.ts, packages/frames.js/src/middleware/stateMiddleware.test.ts, packages/frames.js/src/middleware/stateMiddleware.ts
This PR removes double calling `next()` in `stateMiddleware` if the first call did not return frame definition, which caused route handler to be called twice.
Closes #395
=> fix(frames.js): remove double calling route handler in state middleware

.changeset/real-moons-buy.md, docs/pages/reference/core/Button.mdx, packages/frames.js/src/core/button.ts, packages/frames.js/src/core/index.ts, packages/frames.js/src/core/types.ts, packages/frames.js/src/middleware/renderResponse.test.tsx, packages/frames.js/src/middleware/renderResponse.ts
This PR adds support for plain object button definitions. Also new `button()` helper is provided to improve typescript experience.
=> feat(frames.js): allow plain object as button definitions so React is not requirement

.changeset/tidy-days-joke.md, packages/frames.js/src/frame-parsers/farcaster.ts, packages/frames.js/src/frame-parsers/open-frames.ts
Fixes an error where frame parsing would fail due to invalid OG image despite the rest of the frame being valid.
=> fix(frames.js): warn invalid og image

.changeset/friendly-teachers-change.md, docs/pages/reference/js/types.mdx, packages/frames.js/src/types.ts
Adds missing `attribution` attribute in `TransactionTargetResponse` type
Closes #409
=> fix(frames.js): `attribution` attribute in `TransactionTargetResponse` type

.changeset/six-eels-destroy.md, packages/frames.js/src/frame-parsers/open-frames.test.ts, packages/frames.js/src/frame-parsers/open-frames.ts
Fix issue where open frames parsing was not falling back to fc attributes if present
=> fix: open frames fall back to farcaster buttons if "of:button" not found

.changeset/cool-seals-repair.md, docs/pages/reference/render/use-frame.mdx, packages/render/src/types.ts, packages/render/src/use-fetch-frame.ts, packages/render/src/use-frame.tsx
=> feat(render): allow to override behaviour of redirects, fetch and link button clicks

packages/render/src/collapsed-frame-ui.tsx
Add collapsed frame button rendereding rules according to https://warpcast.com/horsefacts.eth/0x34188947
- Show "View" button if text > 12 characters or multiple buttons present
- Disable button presses (collapsed frame always opens frame modal)
=> fix: collapsed frame rules

.changeset/nice-pianos-smash.md, packages/debugger/app/hooks/use-lens-identity.tsx, packages/debugger/app/hooks/use-xmtp-identity.tsx
This PR fixes XMTP and Lens signers to actually respect `target` passed to them and not infer it from button. This fixes an issue where buttons like `tx` have 2 possible targets.
Fixes #433
=> fix(debugger): respect target passed to signers

.changeset/nine-pears-lie.md, packages/render/src/use-frame.tsx
Don't trigger onSignerlessFramePress for client side buttons (mint, tx) as they do not make a call to the frame server.
=> fix(render): no signer required for client side button actions

.changeset/odd-bats-jam.md, packages/debugger/app/components/protocol-config-button.tsx, packages/debugger/app/debugger-page.tsx, packages/debugger/app/frames/route.ts, packages/debugger/app/hooks/use-anonymous-identity.tsx, packages/frames.js/package.json, packages/frames.js/src/anonymous/index.ts, packages/frames.js/src/middleware/openframes.ts, templates/next-starter-with-examples/app/examples/multi-protocol/frames/frames.ts, templates/next-starter-with-examples/app/examples/multi-protocol/frames/who-am-i/route.tsx
- Adds support for `of:clientProtocol:anonymous` in frames.js `frames.js/anonymous` 
- Sets default open frames middleware call to use anonymous client protocol if no arguments specified
- Adds support for anonymous signers in frames.js debugger
- Updates `multi-protocol` example to accept anonymous open frames requests
=> feat: anonymous open frames signer

packages/debugger/app/components/frame-ui.tsx, packages/render/src/ui/frame.base.tsx, packages/render/src/ui/index.native.tsx, packages/render/src/ui/index.tsx, packages/render/src/ui/types.ts
This PR:
- makes FrameUI generic so user can override style props types
- allows to change `createElement` used to produce jsx, this handles issues when NativeWind essentially uses their own wrapper around createElement
=> feat: allow to override style props type

.changeset/modern-feet-punch.md, docs/pages/reference/core/createFrames.mdx, packages/debugger/app/hooks/use-anonymous-identity.tsx, packages/frames.js/src/anonymous/index.ts, packages/frames.js/src/core/createFrames.ts, packages/frames.js/src/core/types.ts, packages/frames.js/src/lens/index.ts, packages/frames.js/src/middleware/farcaster.test.ts, packages/frames.js/src/middleware/farcaster.ts, packages/frames.js/src/middleware/farcasterHubContext.test.ts, packages/frames.js/src/middleware/farcasterHubContext.ts, packages/frames.js/src/middleware/images-worker/handler.test.tsx, packages/frames.js/src/middleware/images-worker/imagesWorker.test.tsx, packages/frames.js/src/middleware/openframes.test.ts, packages/frames.js/src/middleware/openframes.ts, packages/frames.js/src/middleware/renderResponse.test.tsx, packages/frames.js/src/middleware/walletAddressMiddleware.ts, packages/frames.js/src/xmtp/index.ts, templates/next-starter-with-examples/app/examples/multi-protocol/frames/who-am-i/route.tsx
This PR adds `walletAddress()` method to context so user can get wallet address associated with frame message.
=> feat(frames.js): add walletAddress method to context

.changeset/mighty-dingos-exercise.md, docs/pages/reference/render/headless-ui.mdx, packages/debugger/app/components/frame-debugger.tsx, packages/debugger/app/components/frame-ui.tsx, packages/render/src/types.ts, packages/render/src/ui/frame.base.tsx, packages/render/src/ui/index.native.tsx, packages/render/src/ui/index.tsx, packages/render/src/ui/types.ts, packages/render/src/use-fetch-frame.ts
This PR adds new `Message` component which is rendered in case there is an message and no `sourceFrame`. It also fixes the regression.
=> fix: cast action message regression

.changeset/young-paws-type.md, templates/express/package.json, templates/hono/package.json, templates/next/package.json, templates/remix/package.json
This PR adds missing `dotenv` dependency to some templates.
Closes #463
=> fix(templates): missing dotenv dependency

.changeset/gold-dots-breathe.md, .changeset/olive-eagles-push.md, docs/pages/guides/transactions.mdx, docs/pages/reference/js/getFrameMessage.mdx, docs/pages/reference/js/types.mdx, docs/pages/reference/render/types.mdx, docs/pages/reference/render/use-frame.mdx, packages/debugger/app/debugger-page.tsx, packages/debugger/app/hooks/use-anonymous-identity.tsx, packages/debugger/app/hooks/use-lens-identity.tsx, packages/debugger/app/hooks/use-xmtp-identity.tsx, packages/frames.js/src/anonymous/index.ts, packages/frames.js/src/core/types.ts, packages/frames.js/src/getFrameMessage.ts, packages/frames.js/src/lens/index.ts, packages/frames.js/src/middleware/farcaster.test.ts, packages/frames.js/src/types.ts, packages/frames.js/src/xmtp/index.ts, packages/render/src/farcaster/frames.tsx, packages/render/src/types.ts, packages/render/src/use-fetch-frame.ts, packages/render/src/use-frame-stack.ts, packages/render/src/use-frame.tsx, templates/next-starter-with-examples/app/examples/transactions/frames/frames.ts, templates/next-starter-with-examples/app/examples/transactions/frames/route.tsx, templates/next-starter-with-examples/app/examples/transactions/frames/txdata-self/route.ts
This PR adds `address` property to `ctx.message` that is set to wallet's address used to create a transaction when user presses `tx` button. The `address` is availale in both endpoints defined by `post_url` and `target` props.
=> feat: add address of wallet used to create a transaction to message

.changeset/shy-peaches-accept.md, packages/render/src/hooks/use-storage.ts
This PR fixes an issue when initial value is first set but then when async storage resolves with undefined it was removed.
Now the initial value works fine, each time there is an undefined value (storage doesn't contain a value or the value has been removed), we use initial value.
=> fix: use initial state when value is not stored in storage or is removed from it

.changeset/light-donuts-mix.md, packages/render/src/hooks/use-storage.ts
This PR fixes passing setting a value on storage with setter function if there is no value in storage by providing an initial value.
=> fix: pass initial state to setter if there is no value in storage

.changeset/tough-days-breathe.md, packages/debugger/app/components/farcaster-signer-config.tsx, packages/render/src/identity/farcaster/types.ts, packages/render/src/identity/farcaster/use-farcaster-identity.tsx, packages/render/src/identity/farcaster/use-farcaster-multi-identity.tsx
This PR adds a result to `createSigner()` so we don't need to wait for signer to be updated in state and react to that in effect. This is more convenient, especially when you need to react to that result.
=> feat: return signer approval when creating signer on farcaster

.changeset/flat-dragons-tan.md, packages/frames.js/src/anonymous/index.ts, packages/frames.js/src/getFrameMessage.ts, packages/frames.js/src/middleware/farcaster.test.ts, packages/frames.js/src/types.ts, packages/frames.js/src/xmtp/index.ts
Updates `getFrameMessage` to include the frame url in the return value. By extension this exposes the frame URL in the `ctx.message` object.
=> fix(frames.js): expose frame url in ctx.message

docs/pages/reference/render/use-frame.mdx
removes deprecated method `isFrameValid` from docs
=> fix: update docs to remove is frame valid

docs/pages/cli/creating-a-project-from-template.mdx, docs/pages/index.mdx, packages/create-frames/README.md
A common issue is that builders are running an out of date CLI to create their frames. This ensures they use the latest
=> chore: recommend using latest cli

.changeset/angry-eels-type.md, docs/pages/reference/js/types.mdx, packages/debugger/app/frames/route.ts, packages/frames.js/src/frame-parsers/utils.ts, packages/frames.js/src/getFrame.test.ts, packages/frames.js/src/getFrameFlattened.test.ts, packages/frames.js/src/getFrameFlattened.ts, packages/frames.js/src/types.ts, packages/render/src/use-frame.tsx
=> fix: handle button post_url attribute

.changeset/nine-toes-fetch.md, packages/render/src/ui/frame.base.tsx, packages/render/src/ui/types.ts
=> feat: pass down previous frame to loading screen on frame ui

.changeset/tiny-carrots-shake.md, packages/frames.js/src/core/types.ts, packages/render/src/use-fetch-frame.ts
Fixes https://linear.app/modprotocol/issue/FRA-395/missing-actionposturl-on-cast-action-definition
=> feat: support for cast action postUrl property

.changeset/pretty-mangos-shop.md, packages/debugger/app/components/debugger-console.tsx, packages/debugger/app/debugger-page.tsx
This PR fixes an issue when console.log() could cause infinite render cycle.
=> fix(debugger): avoid infinite rendering cycles when using console.log

.changeset/dry-bulldogs-jog.md, packages/render/src/ui/frame.base.tsx, packages/render/src/ui/types.ts
Exposes the full frame state in UI components in the `render` package.
Example use case: reordering buttons without modifying the frame state (apply the patch and view `http://localhost:3010/?url=http://localhost:3000/examples/basic` in the browser)
```diff
diff --git a/packages/debugger/app/components/frame-ui.tsx b/packages/debugger/app/components/frame-ui.tsx
index 7bb7d10d..78536e5c 100644
--- a/packages/debugger/app/components/frame-ui.tsx
+++ b/packages/debugger/app/components/frame-ui.tsx
@@ -7,6 +7,7 @@ import Image from "next/image";
import defaultImageLoader from "next/dist/shared/lib/image-loader";
import React from "react";
import type { ImageLoaderProps } from "next/dist/shared/lib/image-config";
+import { Frame } from "frames.js";
type Props = Omit<
React.ComponentProps<
@@ …
```
=> feat: expose full frameState in render UI components

.changeset/twelve-adults-greet.md, packages/frames.js/src/frame-parsers/open-frames.test.ts, packages/frames.js/src/frame-parsers/open-frames.ts
This PR adds missing fallback to `fc:frame:post_url` when using `openframes` protocol and `of:post_url` is not available.
=> fix(frames.js): fall back to fc:frame:post_url if of:post_url is not available

.changeset/rich-experts-suffer.md, packages/render/src/ui/frame.base.tsx, packages/render/src/ui/types.ts
Passes button props alongside the button elements to the `FrameButtonContainer` component in case the props need to be transformed or reordered at render time.
=> feat: pass buttons' props separately to FrameButtonContainer

.changeset/good-buckets-work.md, packages/render/src/farcaster/frames.tsx
Fixes an issue where some frame servers would reject the frame message because it is too old. This is because the untrustedData timestamp is expected to be a UNIX timestamp in milliseconds, not a farcaster epoch in seconds (source: https://warpcast.com/horsefacts.eth/0x18fa6881)
=> fix: UNIX timestamp in milliseconds in farcaster untrusted data

.changeset/five-keys-wait.md, packages/debugger/app/components/frame-debugger.tsx
Adds debug shortcuts for frame button links that start with `https://warpcast.com/~/composer-action`
=> feat: debug miniapp frame link shortcut

.changeset/three-buttons-fry.md, packages/render/src/use-frame.tsx
=> fix: only allow http(s) urls in link buttons

.changeset/fair-singers-look.md, packages/render/package.json, packages/render/src/errors.ts, packages/render/src/helpers.ts, packages/render/src/types.ts, packages/render/src/use-fetch-frame.ts, packages/render/src/use-frame-stack.ts, packages/render/src/use-frame.tsx
This PR adds event listeners to `useFrame()` so you have more finer control when implementing an UI feedback.
=> feat: transaction event listeners

.changeset/cool-ties-accept.md, packages/frames.js/src/farcaster/generated/message.ts, packages/frames.js/src/getUserDataForFid.test.ts, packages/frames.js/src/getUserDataForFid.ts, packages/frames.js/src/types.ts
Updates the Message protobuf, which fixes unrecognized user data type errors due to the introduction of new location user data type.
=> feat: support location user data type

.changeset/gentle-beers-jog.md, .changeset/lazy-deers-laugh.md, .changeset/violet-elephants-taste.md, packages/debugger/app/components/action-debugger.tsx, packages/debugger/app/components/composer-form-action-dialog.tsx, packages/render/src/types.ts, templates/next-starter-with-examples/app/examples/transaction-miniapp/frames/actions/miniapp/route.tsx, templates/next-starter-with-examples/app/examples/transaction-miniapp/frames/frames.ts, templates/next-starter-with-examples/app/examples/transaction-miniapp/frames/route.tsx, templates/next-starter-with-examples/app/examples/transaction-miniapp/miniapp/page.tsx, templates/next-starter-with-examples/app/examples/transaction-miniapp/page.tsx, templates/next-starter-with-examples/package.json, yarn.lock
=> feat: handle transactions from composer actions in debugger

packages/frames.js/src/middleware/neynar/neynarValidate.test.ts
=> fix: neynar tests

.changeset/lemon-horses-double.md, packages/frames.js/src/middleware/neynar/index.ts, packages/frames.js/src/middleware/neynar/neynarValidate.test.ts
This PR makes neynar validator less optimistic.
=> fix: deal better with errors in neynar validator middleware

.changeset/real-crabs-heal.md, packages/debugger/app/components/composer-form-action-dialog.tsx, packages/debugger/app/frames/route.ts, templates/next-starter-with-examples/app/examples/transaction-miniapp/miniapp/page.tsx
Implement JSON-RPC requests as per latest spec
=> fix: update miniapp transactions spec implementation

.changeset/hungry-actors-call.md, packages/debugger/app/components/cast-composer.tsx
This PR fixes overflow of long urls in cast embed debugger.
=> fix: prevent long urls in cast embeds from overflowing

.changeset/grumpy-berries-love.md, packages/debugger/app/components/action-debugger.tsx, packages/debugger/app/components/cast-composer.tsx, packages/debugger/app/components/composer-action-debugger.tsx, packages/debugger/app/components/composer-form-action-dialog.tsx, packages/debugger/app/debugger-page.tsx, packages/debugger/app/frames/route.ts, packages/debugger/app/hooks/useFarcasterIdentity.tsx, packages/debugger/app/lib/utils.ts, packages/debugger/app/utils/mock-hub-utils.ts, packages/render/package.json, packages/render/src/errors.ts, packages/render/src/farcaster/frames.tsx, packages/render/src/farcaster/signers.tsx, packages/render/src/helpers.ts, packages/render/src/identity/farcaster/use-farcaster-identity.tsx, packages/render/src/identity/farcaster/use-farcaster-multi-identity.tsx, packages/render/src/mini-app-messages.ts, packages/render/src/next/POST.tsx, packages/render/src/unstable-types.ts, packages/render/src/use-composer-action.ts
This PR adds new `useComposerAction()` hook to simplify building mini apps.
=> feat: mini app support

packages/debugger/app/components/cast-composer.tsx, packages/render/src/unstable-types.ts, packages/render/src/unstable-use-frame.tsx, packages/render/src/use-composer-action.ts
This PR replaces `onConnectWallet` and `connectedAdress` with `resolveAddress` on `useFrame_unstable()` hook.
=> chore: use resolveAddress instead of connectedAddress

.changeset/old-pumas-call.md, packages/render/src/identity/anonymous/index.ts
This PR adds missing export for `AnonymousSignerInstance` type.
=> fix: export missing type from anonymous identity hook

.changeset/serious-phones-judge.md, packages/render/src/identity/farcaster/use-farcaster-identity.tsx, packages/render/src/identity/farcaster/use-farcaster-multi-identity.tsx
This PR adds a `fetchFn` option to override fetch function in farcaster identity hooks.
=> feat: allow to override fetch function in farcaster identity hooks

.changeset/mighty-mugs-refuse.md, packages/frames.js/src/core/utils.test.ts, packages/frames.js/src/core/utils.ts
This PR avoids pathname overwriting when passing in an URLObject with all necessary props to `generateTargetURL()`.
If the user passing in a URL object with all props required to construct a full URL, that means they want to go straight to there without modification. But current behaviour of `generateTargetURL()` overwrite its `pathname` by prepending the `pathname` of `baseUrl`
=> fix: a "complete" URLObject in `target` should be left as it is

.changeset/tasty-moons-repair.md, packages/debugger/package.json, packages/frames.js/package.json, packages/render/package.json, templates/next-starter-with-examples/package.json, yarn.lock
bump lens client due to https://github.com/lens-protocol/lens-sdk/issues/966
I don't think this PR needs a changeset @stephancill ?
=> chore: bump @lens-protocol/client to 2.3.2 to run node ver 22

.changeset/large-baboons-notice.md, packages/render/src/identity/lens/use-lens-identity.tsx
Adds support for Lens development environment in use-lens-identity
=> feat: adds support for Lens development environment in use-lens-identity

.changeset/five-zoos-wash.md, packages/debugger/app/client-info/route.ts, packages/debugger/app/components/farcaster-domain-account-association-dialog.tsx, packages/debugger/app/components/frame-app-debugger.tsx, packages/debugger/package.json, packages/frames.js/package.json, packages/frames.js/src/frame-parsers/farcasterV2.test.ts, packages/frames.js/src/frame-parsers/farcasterV2.ts, packages/render/package.json, packages/render/src/frame-app/types.ts, packages/render/src/use-frame-app.ts, yarn.lock
=> chore: update dependencies and fix debugger issues

.changeset/clean-dragons-return.md, packages/debugger/app/components/frame-app-debugger-view-profile-dialog.tsx, packages/debugger/app/components/frame-app-debugger.tsx, packages/debugger/app/farcaster/user/[fid]/route.ts
This PR implements view profile dialog for frames v2.
=> feat: view profile dialog

.changeset/chilled-spies-vanish.md, package.json, packages/render/src/types.ts, packages/render/src/unstable-types.ts, packages/render/src/unstable-use-frame.tsx
Previously in order to determine when the signer is missing but required by the button action, it requires the devs to add callback `onMissingIdentity` to `useFarcasterMultiIdentity` to determine such event, which is not very straight forward. 
(when signer is missing the hook calls into `frameStae.signerState.onSignerlessFramePress`, which in turns triggers `onMissingIdentity` callback on the `useFarcasterMultiIdentity`)
The PR adds a dedicated `onMissingSigner` callback for `useFrame_unstable`. The callback will be called when the button action requires a signer but signer is not found.
@michalkvasnicak by looking at the code, it feels to me that adding `onTransactionButtonError`/`onPostButtonError` could be confusing, I am worrying the naming could give developers a false impression …
=> feat: add `onMissingSigner` callback

.changeset/slow-pigs-hug.md, packages/render/src/frame-app/iframe.ts, packages/render/src/frame-app/web-view.ts, packages/render/src/use-frame-app.ts
This PR removes forcing frame app url to be `frame.button.action.url` and instead it uses the URL you used to fetch the frame data.
=> fix: pass original frame app url to view

.changeset/popular-bats-relate.md, packages/debugger/app/components/frame-app-debugger-notifications.tsx, packages/debugger/app/components/frame-app-debugger.tsx, packages/debugger/app/components/frame-app.tsx, packages/debugger/app/providers/FrameAppNotificationsManagerProvider.tsx
This PR fixes setting frame app context on reload after you changed anything regarding notifications
=> fix: properly set frame app context on reload

.changeset/fuzzy-cherries-mate.md, packages/debugger/app/components/frame-app.tsx, packages/debugger/app/notifications/types.ts, packages/render/src/frame-app/types.ts, packages/render/src/frame-app/use-resolve-context.ts, packages/render/src/use-frame-app.ts
This PR simplifies how context is set up for `useFrameApp()`. Now it uses only one property `context` instead of 3 and the context can be either an object or a function returning an object.
=> feat: simpler frame app context resolving

.changeset/little-berries-hang.md, packages/frames.js/src/frame-parsers/farcasterV2.ts
In the case of `InvalidJFSHeaderError`, the error is not detected in the debugger and you just see the following image:
This change will catch this specific error for better DX.
Example using the command line:
**Without any change:**
**Including the change**
=> chore: handle `InvalidJFSHeaderError` in `parseManifest`
