framesjs/frames.js

docs/docs/pages/index.mdx
=> Update to correct link https://warpcast.com/~/channel/frames-devs

examples/framesjs-starter/package.json, examples/utils-starter/package.json
- prevents automatic non semver upgrades of people using the starter.
=> fix: proper versions

examples/framesjs-starter/package.json
=> fix: engines

examples/custom-redirects/app/debug/hub/[...hubPath]/route.ts, examples/framesjs-starter/app/debug/hub/[...hubPath]/route.ts
Fixes a bug (theoretically, don't have repro steps) a user was experiencing
=> fix: request header proxying

examples/custom-redirects/app/debug/hub/[...hubPath]/route.ts, examples/framesjs-starter/app/debug/hub/[...hubPath]/route.ts
- bun implements `fetch` differently and validates these certs. These certs are invalid
=> fix: cert issue

examples/framesjs-starter/app/debug/components/frame-debugger.tsx, examples/framesjs-starter/app/debug/page.tsx, packages/frames.js/src/validateFrame.ts
- adds perf validation
- adds image validation
=> feat: add perf, image validation

.changeset/perfect-bottles-begin.md, examples/framesjs-starter/app/debug/components/frame-debugger.tsx
Removes mint warning on debugger page
=> chore: remove mint spec warning

.changeset/friendly-buses-think.md, docs/pages/reference/js/types.mdx, docs/pages/reference/react/FrameInput.mdx, examples/framesjs-starter/app/debug/components/frame-render.tsx, packages/frames.js/src/getFrame.test.ts, packages/frames.js/src/getUserDataForFid.test.ts, packages/frames.js/src/next/server.tsx, packages/frames.js/src/types.ts, packages/frames.js/src/validateFrame.ts
- Add support for `fc:frame:image:aspect_ratio`
- Update fc:image:frame type docs to match spec
=> feat: add support for aspect ratio property

.changeset/fair-books-heal.md, examples/framesjs-starter/app/debug/page.tsx
- Validate that debugger target url starts with http:// or https://
- Improve navigation using nextjs `<Link>` components
=> fix(debugger): url validation and smoother navigation

.changeset/fair-books-heal.md, .changeset/long-cows-matter.md, .changeset/ninety-boxes-suffer.md, .changeset/strong-pans-own.md, docs/pages/index.mdx, examples/framesjs-starter/CHANGELOG.md, examples/framesjs-starter/app/page.tsx, examples/framesjs-starter/package.json, packages/frames.js/CHANGELOG.md, packages/frames.js/package.json, packages/frames.js/src/getFrameFlattened.ts
- fix `getFrameFlattened` to add aspect ratio
=> fix: get frame flattened

.changeset/grumpy-dogs-punch.md, examples/framesjs-starter/app/debug/page.tsx, examples/framesjs-starter/app/examples/multi-page/frames/route.ts, examples/framesjs-starter/app/examples/multi-page/page.tsx
Adds an example that demonstrates a simple unauthenticated flow where the user can cycle through 5 pages of random images with arrow buttons.
=> feat: multi page example

packages/frames.js/package.json, yarn.lock
- updates farcaster/core package dependency
=> fix: bump fc package

docs/pages/reference/react/FrameButton.mdx, docs/pages/reference/react/FrameContainer.mdx, docs/pages/reference/react/FrameImage.mdx, docs/pages/reference/react/FrameInput.mdx
=> fix: docs rendering

.changeset/neat-dragons-applaud.md, examples/framesjs-starter/app/debug/components/frame-render.tsx, packages/frames.js/src/types.ts, packages/frames.js/src/validateFrameMessage.ts
- change mint icon
- export frameversion type
- more helpful error msg
=> fix: small fixes

.changeset/dirty-ducks-trade.md, docs/pages/reference/js/types.mdx, examples/framesjs-starter/app/debug/hub/[...hubPath]/route.ts, packages/frames.js/src/getAddressForFid.ts, packages/frames.js/src/getFrameMessage.ts, packages/frames.js/src/getUserDataForFid.ts, packages/frames.js/src/types.ts, packages/frames.js/src/validateFrameMessage.ts
Switch from https://api.neynar.com:2281 to https://hub-api.neynar.com to improve performance.
=> chore: update fallback neynar hub api url

docs/pages/reference/react/FrameButton.mdx, docs/pages/reference/react/FrameImage.mdx, docs/pages/reference/react/FrameInput.mdx
Fixes instances of `FrameButton` in docs which use outdated props.
=> fix: button docs

.changeset/eighty-rabbits-joke.md, examples/framesjs-starter/.gitignore, examples/framesjs-starter/app/debug/components/mock-hub-config.tsx, examples/framesjs-starter/app/debug/frame-action/route.ts, examples/framesjs-starter/app/debug/hub/[...hubPath]/route.ts, examples/framesjs-starter/app/debug/lib/utils.ts, examples/framesjs-starter/app/debug/page.tsx, examples/framesjs-starter/app/page.tsx
Adds an interface for users to mock basic hub state in the debugger e.g. user follow and reaction state
=> feat(debugger): mock hub state

.changeset/itchy-deers-beg.md, examples/framesjs-starter/package.json, package.json, packages/frames.js/package.json, packages/frames.js/src/farcaster/generated/message.ts, packages/frames.js/src/farcaster/generated/username_proof.ts, packages/frames.js/src/farcaster/index.ts, packages/frames.js/src/farcaster/types.ts, packages/frames.js/src/getFrameMessage.ts, packages/frames.js/src/getUserDataForFid.ts, packages/frames.js/src/next/server.tsx, packages/frames.js/src/utils.ts, packages/frames.js/src/validateFrameMessage.ts, yarn.lock
- Removes @farcaster/core dependency from frames.js
@farcaster/core is required by the debugger, so remains a dependency of framesjs-starter
=> chore: remove @farcaster/core dependency from frames.js

.changeset/angry-dragons-mix.md, examples/framesjs-starter/app/debug/components/mock-hub-config.tsx, examples/framesjs-starter/app/debug/page.tsx
Fixes framesjs-starter build failing due to incorrect types.
=> fix: mock hub config partial

.changeset/twenty-kids-shop.md, packages/frames.js/package.json, packages/frames.js/src/getFrame.test.ts, packages/frames.js/src/getFrameFlattened.ts, packages/frames.js/src/getFrameHtml.ts, packages/frames.js/src/next/server.tsx, packages/frames.js/src/types.ts, packages/frames.js/src/validateFrame.ts, packages/frames.js/src/xmtp/index.ts, yarn.lock
Support multiple client protocols via `of:accepts:`
=> feat: support multiple client protocols via `of:accepts:` 

docs/pages/reference/js/types.mdx, docs/pages/reference/js/xmtp/getXmtpFrameMessage.mdx, docs/pages/reference/js/xmtp/isXmtpFrameActionPayload.mdx, examples/framesjs-starter/app/debug/page.tsx, examples/framesjs-starter/app/examples/multi-protocol/frames/route.ts, examples/framesjs-starter/app/examples/multi-protocol/page.tsx, examples/framesjs-starter/package.json, packages/frames.js/src/next/server.tsx, packages/frames.js/src/types.ts
- Fixes bug where `FrameContainer` component was not outputting the `of:accepts:*` tags
- Adds multi-protocol example
- Adds docs for xmtp functions and types
=> feat: of:accepts improvements

.changeset/modern-wasps-fail.md, package.json, packages/frames.js/jest.config.js, packages/frames.js/src/default.ts, packages/frames.js/src/getAddressForFid.test.ts, packages/frames.js/src/getAddressForFid.ts, packages/frames.js/src/getAddressesForFid.test.ts, packages/frames.js/src/getAddressesForFid.ts, packages/frames.js/src/getFrameMessage.ts, packages/frames.js/src/getUserDataForFid.test.ts, packages/frames.js/src/getUserDataForFid.ts, packages/frames.js/src/validateFrameMessage.ts, yarn.lock
This PR fixes handling non json responses from hub api and also adds few tests.
=> fix: properly handle hub api responses

docs/pages/reference/js/xmtp/index.mdx, docs/vocs.config.tsx, examples/framesjs-starter/app/examples/multi-protocol/page.tsx
=> fix: docs and xmtp guide

docs/pages/guides/display-frames.mdx, docs/pages/reference/render/frame-ui.mdx, docs/pages/reference/render/use-frame.mdx, packages/frames.js/package.json, packages/frames.js/src/render/frame-ui.tsx, packages/frames.js/src/render/index.tsx, packages/frames.js/src/render/use-frame.tsx
=> fixes use-frame

examples/framesjs-starter/dev-script.js, examples/framesjs-starter/package.json, package.json, packages/debugger/app/components/create-signer.tsx, packages/debugger/app/page.tsx, yarn.lock
- Add debugger to frames.js starter and open it automatically when running dev script
- Differentiate between dev script in monorepo and standalone
=> chore: standalone debugger qol improvements

packages/frames.js/src/next/server.tsx
Fixes issues related to NEXT_PUBLIC_HOST fallback on next/server
=> fix: next/server headers fallback

.changeset/tame-news-battle.md, examples/framesjs-starter/scripts/dev-script.js, packages/debugger/.env.sample, packages/debugger/app/hooks/use-farcaster-identity.tsx, packages/debugger/app/signer/route.ts
- fixes signer flow in new debugger
-
=> fix: signer flow in debugger

packages/debugger/app/components/create-signer.tsx
=> fix: sign in ux

.changeset/orange-trainers-confess.md, packages/debugger/bin/debugger.js
=> fix: fallback to env variables

packages/frames.js/README.md
The link to the debugger is broken.
=> fixing broken link

.changeset/clean-goats-mix.md, docs/pages/reference/js/types.mdx, packages/frames.js/src/types.ts
- adds missing type to the post body
=> fix: add transaction id type to body

.changeset/sour-garlics-sin.md, packages/frames.js/src/getFrame.ts
- improves error message for when the user accidentally passes an image without an http at the start
=> fix: image type error

.changeset/sweet-rats-clap.md, docs/pages/reference/js/types.mdx, packages/frames.js/src/types.ts
=> fix: transaction id type

.changeset/popular-parents-cross.md, examples/framesjs-starter/app/examples/only-followers-can-mint/frames/route.ts, examples/framesjs-starter/app/examples/only-followers-can-mint/page.tsx, examples/framesjs-starter/app/examples/page.tsx
This PR adds simple only followers can mint example.
=> feat: only followers can mint example

packages/debugger/app/components/frame-debugger.tsx
=> fix: tx-stable

packages/frames.js/src/render/frame-ui.tsx
- replace icon with warpcast icon
=> chore: tx icon

.changeset/giant-hounds-float.md, docs/pages/reference/js/getFrame.mdx, packages/frames.js/src/getFrame.test.ts, packages/frames.js/src/getFrame.ts
Update `getFrame` to also detect and parse Open Frames tags according to the [spec](https://github.com/open-frames/standard)
=> feat: open frames tags parsing

.changeset/eighty-starfishes-wait.md, docs/pages/reference/js/types.mdx, packages/frames.js/package.json, packages/frames.js/src/getFrameMessage.ts, packages/frames.js/src/render/farcaster/frames.tsx, packages/frames.js/src/render/index.tsx, packages/frames.js/src/render/use-frame.tsx, packages/frames.js/src/types.ts, yarn.lock
Adds the connected address to transaction data requests.
=> feat: frame tx connect address

.changeset/blue-crabs-repair.md, .changeset/nervous-wolves-flash.md, .changeset/popular-parents-cross.md, docs/pages/reference/render/types.mdx, examples/framesjs-starter/CHANGELOG.md, examples/framesjs-starter/package.json, packages/debugger/app/hooks/use-farcaster-identity.tsx, packages/debugger/app/page.tsx, packages/frames.js/CHANGELOG.md, packages/frames.js/package.json, packages/frames.js/src/render/types.ts, packages/frames.js/src/render/use-frame.tsx
- separates the signer loading state from the frame loading state
Unblocks https://github.com/mod-protocol/frames-iframe/pull/1
=> fix: decouples frames loading from signer loading states

packages/frames.js/src/core/components.ts, packages/frames.js/src/core/middleware/renderResponse.test.tsx, packages/frames.js/src/core/middleware/renderResponse.tsx, packages/frames.js/src/getFrame.ts, packages/frames.js/src/types.ts
=> feat: add new api tx button rendering

packages/remix/README.md, packages/remix/jest.config.js, packages/remix/package.json, packages/remix/src/fetchMetaData.test.ts, packages/remix/src/fetchMetaData.ts, packages/remix/src/index.test.ts, packages/remix/src/index.ts, packages/remix/tsconfig.json, yarn.lock
=> feat: remix adapter

packages/express/README.md, packages/express/jest.config.js, packages/express/package.json, packages/express/src/index.test.tsx, packages/express/src/index.ts, packages/express/tsconfig.json, yarn.lock
This PR adds express.js adapter
=> feat: express adapter

packages/frames.js/src/core/createFrames.ts, packages/frames.js/src/core/index.ts, packages/frames.js/src/core/types.ts, packages/hono/README.md, packages/hono/jest.config.js, packages/hono/package.json, packages/hono/src/index.test.tsx, packages/hono/src/index.ts, packages/hono/tsconfig.json, yarn.lock
=> feat: hono adapter

packages/express/src/index.ts, packages/frames.js/src/core/types.ts, packages/hono/src/index.test.tsx, packages/hono/src/index.ts, packages/next/src/index.ts, packages/remix/src/index.ts
This PR improves types on `createFrames` functions and adds tsdocs with examples.
=> chore: improve types and docs

.changeset/late-laws-greet.md, packages/frames.js/package.json, packages/frames.js/src/core/errors.ts, packages/frames.js/src/core/middleware/openframes.test.ts, packages/frames.js/src/core/middleware/openframes.ts, packages/frames.js/src/core/middleware/parseFramesMessage.ts, packages/frames.js/src/core/middleware/renderResponse.tsx, packages/frames.js/src/core/types.ts, packages/frames.js/src/core/utils.ts, packages/frames.js/src/xmtp/index.ts, yarn.lock
Adds middleware which allows frames to parse Open Frames messages and automatically inject `of:accepts` tags based on the messages they parse.
=> feat: openframes middleware

packages/frames.js/src/core/createFrames.test.ts, packages/frames.js/src/core/createFrames.ts, packages/frames.js/src/core/middleware/concurrentMiddleware.ts, packages/frames.js/src/core/middleware/framesjsMiddleware.ts, packages/frames.js/src/core/middleware/openframes.test.ts, packages/frames.js/src/core/middleware/openframes.ts, packages/frames.js/src/core/middleware/parseFramesMessage.test.ts, packages/frames.js/src/core/middleware/parseFramesMessage.ts, packages/frames.js/src/core/middleware/renderResponse.test.tsx, packages/frames.js/src/core/middleware/renderResponse.tsx, packages/frames.js/src/core/middleware/stateMiddleware.test.ts, packages/frames.js/src/core/middleware/stateMiddleware.ts, packages/frames.js/src/core/types.ts, packages/frames.js/src/core/utils.ts, packages/frames.js/src/express/index.ts, packages/frames.js/src/hono/index.ts, packages/frames.js/src/next/index.ts, packages/frames.js/src/remix/index.ts
This PR adds generic support for state
=> feat: make state also undefined if initial state is not passed

packages/frames.js/src/core/createFrames.test.ts, packages/frames.js/src/core/createFrames.ts, packages/frames.js/src/core/middleware/framesjsMiddleware.test.ts, packages/frames.js/src/core/middleware/framesjsMiddleware.ts, packages/frames.js/src/core/middleware/renderResponse.test.tsx, packages/frames.js/src/core/middleware/renderResponse.tsx, packages/frames.js/src/core/types.ts
- renames `ctx.currentURL` to `ctx.url`
=> feat: rename current url to url

examples/framesjs-starter/app/examples/new-api-cache-control/frames/route.tsx, examples/framesjs-starter/app/examples/new-api-cache-control/page.tsx
Current time cache control example
=> feat: example cache control

.changeset/many-laws-kneel.md, packages/frames.js/src/next/fetchMetadata.ts
Fixes nextjs builds by handling resource being unavailable during build time.
=> fix: nextjs prerender build

.changeset/small-dolphins-speak.md, examples/framesjs-starter/app/debug.ts, examples/framesjs-starter/app/examples/new-api-cache-control/page.tsx, examples/framesjs-starter/app/examples/new-api-mint-button/page.tsx, examples/framesjs-starter/app/examples/new-api-multi-page/page.tsx, examples/framesjs-starter/app/examples/new-api-multi-protocol/page.tsx, examples/framesjs-starter/app/examples/new-api-slow-request/page.tsx, examples/framesjs-starter/app/examples/new-api-transaction/page.tsx, examples/framesjs-starter/app/examples/new-api/page.tsx, examples/framesjs-starter/app/utils.ts, packages/frames.js/src/next/fetchMetadata.ts, packages/frames.js/src/next/getCurrentUrl.test.ts, packages/frames.js/src/next/getCurrentUrl.ts, packages/frames.js/src/next/index.ts
This PR fixes missing full URL in nextjs api request
=> fix: add url to nextjs handler

.changeset/famous-items-travel.md, examples/framesjs-starter/app/examples/new-api-multi-page/frames/route.tsx
=> fix: new multi page example base url

.changeset/blue-files-divide.md, packages/debugger/app/providers.tsx
- adds testnets to the debugger
=> feat: testnets in debugger

.changeset/slimy-turtles-train.md, docs/pages/guides/create-frame.mdx, docs/pages/index.mdx, packages/frames.js/README.md
=> fix: generateMetadata example in docs, readme instructions

.changeset/silly-hornets-cough.md, packages/frames.js/src/core/components.ts
=> fix: remove unused button state prop

docs/pages/guides/middleware.mdx, docs/pages/guides/multiple-frames.mdx
=> fix: frames docs exports

.changeset/lucky-rice-accept.md, packages/frames.js/src/render/use-frame.tsx
Updates the functionality of the render export's `onMintFallback` function, which incorrectly redirects to the mint target
=> fix(render): mint fallback message

examples/framesjs-starter/app/examples/new-api-post-redirect/frames/route.tsx, examples/framesjs-starter/app/examples/new-api-post-redirect/page.tsx, examples/framesjs-starter/app/examples/page.tsx
=> chore: add post redirect example

.changeset/slow-turtles-smile.md, packages/frames.js/package.json, packages/frames.js/src/farcaster/generated/message.ts, packages/frames.js/src/farcaster/generated/username_proof.ts, packages/frames.js/src/farcaster/index.ts, packages/frames.js/src/farcaster/types.ts, packages/frames.js/src/getFrameMessage.ts, packages/frames.js/src/getUserDataForFid.ts, packages/frames.js/src/middleware/farcaster.test.ts, packages/frames.js/src/middleware/farcasterHubContext.test.ts, packages/frames.js/src/next/server.tsx, packages/frames.js/src/utils.ts, packages/frames.js/src/validateFrameMessage.ts
Removes @farcaster/core dependency from frames.js
Depends on #237
=> chore: remove farcaster core again

.changeset/healthy-chairs-hammer.md, docs/pages/guides/open-frames.mdx, docs/pages/guides/security.mdx, docs/pages/middleware/farcasterHubContext.mdx, docs/pages/middleware/openframes.mdx, docs/vocs.config.tsx
Adds documentation for verifying messages and middleware (`farcasterHubContext` and `openframes`)
=> docs: verification middleware

packages/frames.js/src/next/getCurrentUrl.ts
Patch for #235 which hasn't been released yet so no changeset necessary.
=> fix: getcurrenturl parsed app url

packages/debugger/app/page.tsx
- Adds logs to the debugger to help devs that think logs will show up in browser
=> chore: devtools logs

.changeset/olive-kangaroos-talk.md, packages/frames.js/src/next/server.tsx
This PR marks old next api as deprecated
=> chore: deprecate old next api

.changeset/sweet-rivers-join.md, examples/framesjs-starter/app/examples/new-api-custom-middleware/frames/frames.ts, packages/frames.js/package.json
Exports new api types and utils via frames.js/types and frames.js/utils
=> fix: expose new types utils

.github/workflows/github-actions.yml
Add ignore_paths with docs and changesets github actions
=> fix: ignore docs and changesets for github actions

.changeset/tidy-cheetahs-cover.md, examples/framesjs-starter/app/frames/frames.ts, examples/framesjs-starter/app/frames/route.ts, examples/framesjs-starter/app/frames/route.tsx, examples/framesjs-starter/app/page.tsx
Updates the starter frame to use the new API with a simple counter example
=> feat: update starter frame

.changeset/light-fireants-rest.md, packages/frames.js/src/middleware/openframes.test.ts, packages/frames.js/src/middleware/renderResponse.ts
Adds support for relative URLs in the image frame definition
=> feat: relative url support for images

.changeset/warm-kangaroos-retire.md, docs/pages/guides/caching.mdx, examples/framesjs-starter/app/examples/new-api-cache-control/frames/frames.ts, examples/framesjs-starter/app/examples/new-api-cache-control/frames/images/current-time/route.tsx, examples/framesjs-starter/app/examples/new-api-cache-control/frames/route.tsx
Provides a working cache control example. Depends on #269
=> fix: cache-control example

.changeset/rotten-taxis-whisper.md, templates/cloudflare-worker/package.json, templates/express/package.json, templates/hono/package.json, templates/next-starter-with-examples/package.json, templates/next-utils-starter/package.json, templates/next/package.json, templates/remix/package.json
This PR bumps template dependency versions
=> fix: bump template versions

.changeset/clever-impalas-notice.md, templates/next/app/frames/route.tsx
This PR adds missing `basePath` to `next` template.
=> fix: add missing basePath to next template

.changeset/dirty-wombats-hunt.md, packages/frames.js/src/getFrameMessage.test.ts, packages/frames.js/src/validateFrameMessage.ts
=> fix: validateFrameMessage bug

.changeset/pink-pots-teach.md, examples/framesjs-starter/app/examples/new-api-transaction/txdata/route.ts, examples/framesjs-starter/app/examples/transaction/txdata/route.ts, examples/framesjs-starter/package.json, yarn.lock
Removes unused packages in framesjs-starter
=> fix: remove unused packages starter

docs/pages/reference/core/next-pages-router/index.mdx, docs/pages/reference/core/next/index.mdx, docs/vocs.config.tsx, examples/framesjs-starter/pages/api/frames/frames.ts, examples/framesjs-starter/pages/api/frames/index.tsx, examples/framesjs-starter/pages/api/frames/next/index.tsx, examples/framesjs-starter/pages/examples/pages-router/index.tsx
This PR adds next pages router guide to docs
=> docs: next pages router

.changeset/cyan-forks-beg.md, examples/framesjs-starter/package.json, examples/utils-starter/package.json, packages/debugger/package.json, packages/render/package.json, templates/cloudflare-worker/package.json, templates/express/package.json, templates/hono/package.json, templates/next-starter-with-examples/package.json, templates/next-utils-starter/package.json, templates/next/package.json, templates/remix/package.json
=> chore: bump frames.js version in templates/packages

.changeset/four-deers-camp.md, packages/frames.js/src/middleware/farcaster.ts, packages/frames.js/src/middleware/farcasterHubContext.ts, packages/frames.js/src/middleware/images-worker/imagesWorker.test.tsx, packages/frames.js/src/middleware/images-worker/index.ts, packages/frames.js/src/middleware/images-worker/next/index.tsx, packages/frames.js/src/middleware/openframes.ts, templates/next-starter-with-examples/app/examples/new-api-multi-protocol/frames/frames.ts, templates/next-starter-with-examples/app/examples/new-api-multi-protocol/frames/images/route.tsx
This patch fixes issues with open frames rendering in XMTP clients
=> fix: openframes XMTP client compatibility

.changeset/smart-ads-walk.md, packages/frames.js/src/middleware/farcaster.ts, packages/frames.js/src/middleware/farcasterHubContext.ts
=> fix: remove error from farcaster middleware log

docs/pages/troubleshooting.mdx
This PR adds troubleshoot section for next.js invalid url error.
=> docs: troubleshoot invalid url

.changeset/grumpy-poets-crash.md, packages/create-frames/create.js, packages/create-frames/utils/getTemplates.js, templates/metadata.json
This PR fixes invalid property used to set initial value for template selection. Also it changes how it is specified so we can further improve it in the future if necessary.
=> fix: properly set default template for create-frames CLI

docs/pages/reference/js/getFrame.mdx, docs/vocs.config.tsx
=> fix: docs links

.changeset/real-deers-impress.md, packages/debugger/app/page.tsx
=> fix: handle value undefined in tx data

.changeset/friendly-dodos-carry.md, templates/next-starter-with-examples/app/examples/new-api-cast-actions/frames/actions/check-fid/route.tsx, templates/next-starter-with-examples/app/examples/new-api-cast-actions/frames/frames.ts, templates/next-starter-with-examples/app/examples/new-api-cast-actions/frames/route.tsx, templates/next-starter-with-examples/app/examples/new-api-cast-actions/utils.ts
Update cast action example to use v2 deep link URLs
=> feat: v2 action url deeplink example

.changeset/gentle-dogs-own.md, docs/pages/guides/image-generation.mdx
=> docs: add link to custom fonts example

package.json, yarn.lock
=> chore: bump turbo version

.changeset/friendly-rice-know.md, packages/frames.js/src/types.ts
Fix transaction params type to have optional `value`, matching spec.
=> fix: optional transaction value param

.changeset/selfish-hounds-doubt.md, packages/debugger/app/actions/farcaster.ts, packages/debugger/app/actions/getAction.ts, packages/debugger/app/actions/parseActionWithReports.ts, packages/debugger/app/actions/parsing/index.ts, packages/debugger/app/actions/parsing/reporter.ts, packages/debugger/app/actions/parsing/types.ts, packages/debugger/app/actions/parsing/utils.ts, packages/debugger/app/actions/types.ts, packages/debugger/app/actions/use-action.tsx, packages/debugger/app/components/action-debugger.tsx, packages/debugger/app/components/frame-debugger.tsx, packages/debugger/app/components/octicons.tsx, packages/debugger/app/frames/route.ts, packages/debugger/app/page.tsx, packages/debugger/package.json, packages/frames.js/package.json, packages/frames.js/src/frame-parsers/index.ts, packages/frames.js/src/frame-parsers/reporter.ts, packages/frames.js/src/frame-parsers/types.ts, packages/frames.js/src/frame-parsers/utils.ts, packages/frames.js/src/types.ts, packages/render/src/next/POST.tsx, packages/render/src/types.ts, packages/render/src/use-frame.tsx, templates/next-starter-with-examples/app/examples/new-api-cast-actions/frames/actions/check-fid-frame/route.tsx, templates/next-starter-with-examples/app/examples/new-api-cast-actions/frames/check-fid/route.tsx, templates/next-starter-with-examples/app/examples/new-api-cast-actions/frames/route.tsx, yarn.lock
=> feat: actions support in debugger

.changeset/eleven-jeans-reflect.md, packages/debugger/app/components/farcaster-signer-config.tsx, packages/debugger/app/components/protocol-config-button.tsx, packages/debugger/app/hooks/use-farcaster-identity.tsx
=> fix: debugger protocol selection improvements

.changeset/polite-mangos-promise.md, docs/pages/reference/core/remix/index.mdx
Fix typo in Remix integration code example.
=> Fix typo in Remix integration code example

.changeset/sharp-chicken-serve.md, packages/debugger/app/providers.tsx, packages/debugger/package.json, yarn.lock
- Add support for degen chain
- Remove testnets with no corresponding supported mainnet
=> feat: add degen chain support

.changeset/nasty-lions-decide.md, docs/pages/guides/debugger.mdx
=> docs: update debugger docs

.changeset/eleven-pears-unite.md, .changeset/swift-rivers-march.md, packages/debugger/.env.sample, packages/debugger/app/hooks/use-farcaster-identity.tsx, packages/debugger/app/signer/route.ts
Add `"Access-Control-Allow-Origin": "*"` to debugger signer response in preparation for delegating signer metadata signatures to hosted debugger
=> fix: debugger signer cors allow all

.changeset/honest-insects-enjoy.md, packages/debugger/@/components/ui/tooltip.tsx, packages/debugger/app/components/action-debugger.tsx, packages/debugger/app/components/frame-debugger.tsx, packages/debugger/app/components/protocol-config-button.tsx, packages/debugger/app/components/with-tooltip.tsx, packages/debugger/app/layout.tsx, packages/debugger/package.json, yarn.lock
This PR adds tooltips to buttons in debugger
=> feat: add button tooltips to debugger

.changeset/selfish-paws-greet.md, packages/debugger/app/actions/use-action.tsx, packages/debugger/app/page.tsx, packages/render/src/types.ts, packages/render/src/use-frame.tsx
This PR fixes double click behaviour when changing debug url in the middle of debugging session.
=> fix(debugger): do not require double click when changing debug url in the middle of debugging session

.changeset/new-crabs-bake.md, packages/create-frames/create.js, packages/create-frames/utils/git.js
This PR adds git repository initialisation with initial commit when user creates a project using `create-frames`.
=> feat(create-frames): initialize git repository on project creation

.changeset/tasty-peaches-knock.md, packages/debugger/.env.sample, packages/debugger/app/hooks/use-farcaster-identity.tsx, packages/debugger/app/signer/route.ts, packages/debugger/bin/debugger.js, packages/debugger/globals.d.ts, packages/debugger/tsconfig.json
This PR adds a fallback to hoster signer in case no signer url nor fid and mnemonic are provided.
=> feat(debugger): fallback to hosted signer

.changeset/shy-peas-try.md, packages/debugger/@/components/ui/toast.tsx, packages/debugger/@/components/ui/toaster.tsx, packages/debugger/@/components/ui/use-toast.ts, packages/debugger/app/components/protocol-config-button.tsx, packages/debugger/app/hooks/use-farcaster-identity.tsx, packages/debugger/app/layout.tsx, packages/debugger/app/page.tsx, packages/debugger/package.json, yarn.lock
This PR improves debugger UX by providing actionable feedback to a user.
=> feat(debugger): improve ux by actionable notifications

.changeset/clean-llamas-jog.md, packages/debugger/app/components/protocol-config-button.tsx, packages/debugger/app/hooks/use-farcaster-identity.tsx
This PR fixes missing farcaster signer creation.
=> fix(debugger): invoke farcaster signer creation on sign in press

docs/pages/guides/multiple-frames.mdx
https://warpcast.com/rezaisgoat.eth/0xc095ec6d
=> chore: docs multi page

.changeset/moody-fans-beam.md, packages/debugger/app/components/farcaster-signer-config.tsx, packages/debugger/app/hooks/use-farcaster-identity.tsx
=> fix(debugger): Open URL button should be a proper link

docs/pages/guides/apps/display-frames.mdx, docs/pages/reference/render/use-frame.mdx
- fixes the docs to add the missing `connectedAddress` property
=> chore: fix render frames docs

.changeset/few-vans-fail.md, packages/debugger/app/page.tsx
Fixes an issue in debugger where the connected address would be overridden by the fallback context address.
=> fix(debugger): connected address

docs/vocs.config.tsx
This PR adds missing `of:accepts` meta tag to docs.
=> fix(docs): add missing of:accepts meta tag

.changeset/five-ducks-thank.md, packages/frames.js/src/core/types.ts, packages/frames.js/src/middleware/renderResponse.test.tsx, packages/render/package.json
This PR improves developer experience for user who use typescript and want to define buttons as conditional arrays, etc. 
Buttons are still validated in runtime, so there is no need to also check that on type level if that makes definining buttons complicated because of conditions.
=> feat(frames.js): improve typescript experience by allowing array of buttons instead of tuple

.changeset/curvy-adults-repair.md, packages/debugger/app/providers.tsx
=> feat(debugger): enable gnosis chain

docs/vocs.config.tsx
=> fix(docs): of:version tag

.changeset/healthy-bears-smile.md, .changeset/pretty-buttons-lie.md, .changeset/three-cheetahs-invent.md, docs/pages/guides/middleware.mdx, docs/pages/guides/open-frames.mdx, docs/pages/reference/js/lens/getLensFrameMessage.mdx, docs/pages/reference/js/lens/index.mdx, docs/pages/reference/js/lens/isLensFrameActionPayload.mdx, docs/vocs.config.tsx, packages/debugger/app/components/lens-profile-select.tsx, packages/debugger/app/components/protocol-config-button.tsx, packages/debugger/app/constants.ts, packages/debugger/app/globals.css, packages/debugger/app/hooks/use-lens-context.tsx, packages/debugger/app/hooks/use-lens-identity.tsx, packages/debugger/app/hub/[...hubPath]/route.ts, packages/debugger/app/page.tsx, packages/debugger/package.json, packages/frames.js/package.json, packages/frames.js/src/lens/index.ts, templates/next-starter-with-examples/app/examples/multi-protocol/frames/frames.ts, templates/next-starter-with-examples/app/examples/multi-protocol/frames/who-am-i/route.tsx, templates/next-starter-with-examples/package.json, yarn.lock
Add support for [Lens frame specification](https://github.com/lens-frames). Export `isLensFrameActionPayload` and `getLensFrameMessage` (using Lens client SDK for authentication) functions in frames.js package, update docs, update `multi-protocol` example.
=> feat: lens open frames

.changeset/loud-scissors-report.md, .changeset/shaggy-pots-perform.md, packages/frames.js/src/middleware/images-worker/handler.tsx, templates/next-starter-with-examples/app/examples/images-worker/frames/route.tsx, templates/next-starter-with-examples/app/examples/images-worker/images/route.tsx
Fixes missing type attributes on images worker options
=> fix: images worker options type

docs/vocs.config.tsx
Fix docs frame page on button press
=> fix: frame page on button click

packages/frames.js/README.md
Fix broken link to debugger docs in README
=> fix: readme debugger docs link

.changeset/strange-llamas-approve.md, packages/debugger/package.json, yarn.lock
Bumps rainbowkit, wagmi, and viem for smart wallet support.
=> chore(debugger): bump rainbowkit,wagmi,viem

.changeset/cold-bulldogs-scream.md, .changeset/fast-shirts-help.md, .changeset/nasty-paws-rule.md, .changeset/rare-olives-stare.md, packages/debugger/app/components/frame-debugger-examples-section.tsx, packages/debugger/app/components/frame-debugger-request-details.tsx, packages/debugger/app/components/frame-debugger.tsx, packages/debugger/app/debugger-page.tsx, packages/debugger/app/frames/route.ts, packages/debugger/app/page.tsx, packages/debugger/app/utils/url-search-params-to-object.ts, packages/render/src/frame-ui.tsx, packages/render/src/next/POST.tsx, packages/render/src/types.ts, packages/render/src/use-fetch-frame.ts, packages/render/src/use-frame-stack.ts
=> fix: properly handle redirects

.changeset/wise-geese-knock.md, packages/frames.js/package.json
This PR adds export for `node-server-helpers`
=> feat(frames.js): export node-server-helpers

.changeset/honest-walls-act.md, packages/frames.js/src/middleware/openframes.test.ts, packages/frames.js/src/middleware/openframes.ts, templates/next-starter-with-examples/app/examples/multi-protocol/frames/frames.ts
This PR fixes open frames body type.
=> fix: open frames body type

.changeset/khaki-cars-bathe.md, docs/pages/examples/wallet-signatures.mdx, docs/pages/guides/transactions.mdx, docs/pages/guides/wallet-signatures.mdx, docs/pages/reference/core/Button.mdx, docs/pages/reference/core/transaction.mdx, docs/pages/reference/js/types.mdx, docs/vocs.config.tsx, packages/debugger/app/debugger-page.tsx, packages/frames.js/src/types.ts, packages/render/src/types.ts, packages/render/src/use-fetch-frame.ts, packages/render/src/use-frame.tsx, templates/next-starter-with-examples/app/examples/wallet-signatures/frames/frames.ts, templates/next-starter-with-examples/app/examples/wallet-signatures/frames/route.tsx, templates/next-starter-with-examples/app/examples/wallet-signatures/frames/signature-data/route.ts, templates/next-starter-with-examples/app/examples/wallet-signatures/page.tsx
This PR implements wallet signatures.
=> feat: wallet signatures

.changeset/neat-chicken-hear.md, packages/frames.js/src/core/types.ts, packages/frames.js/src/getFrameFlattened.ts, packages/frames.js/src/getFrameHtml.ts, packages/frames.js/src/middleware/renderResponse.ts
Includes frame title from frame definition in frame metadata
=> fix: frame og title

.changeset/real-wasps-obey.md, .changeset/silver-peaches-accept.md, docs/pages/examples/dynamic-routes.mdx, docs/pages/guides/dynamic-routes.mdx, docs/vocs.config.tsx, templates/next-starter-with-examples/app/examples/dynamic-routes/frames/[id]/route.tsx, templates/next-starter-with-examples/app/examples/dynamic-routes/frames/frames.ts, templates/next-starter-with-examples/app/examples/dynamic-routes/frames/route.tsx, templates/next-starter-with-examples/app/examples/dynamic-routes/page.tsx
=> feat: dynamic routes example and docs

docs/pages/guides/open-frames.mdx
Adds documentation for unauthenticated frames.
=> docs: unauthenticated frames

docs/pages/examples/composer-actions.mdx, docs/vocs.config.tsx
=> fix: docs typos

docs/vocs.config.tsx
=> fix: broken docs link

.changeset/hip-dodos-pull.md, packages/frames.js/src/core/errors.ts, packages/frames.js/src/getFrameMessage.test.ts, packages/frames.js/src/getFrameMessage.ts, packages/frames.js/src/lens/index.ts, packages/frames.js/src/lens/lens.test.ts
This PR improves message parsing errors.
=> feat: improve message parsing errors

.changeset/nasty-dogs-shave.md, packages/debugger/app/components/cast-composer.tsx, packages/frames.js/src/core/types.ts, packages/frames.js/src/middleware/warpcastComposerActionState.test.ts, packages/frames.js/src/middleware/warpcastComposerActionState.ts, packages/render/src/use-fetch-frame.ts
This PR fixes invalid composer action state parsing.
=> fix: composer action state parsing

packages/frames.js/src/frame-parsers/utils.test.ts, packages/frames.js/src/frame-parsers/utils.ts
https://warpcast.com/horsefacts.eth/0x6d4028e1
=> fix: image validation mimetypes

docs/vocs.config.tsx
This PR adds support for anonymous frame protocol to docs.
=> docs: support anonymous frame

.changeset/shy-mirrors-flow.md, packages/debugger/app/debugger-page.tsx, packages/frames.js/src/core/cast-actions.ts, packages/frames.js/src/core/types.ts, packages/frames.js/src/types.ts, templates/next-starter-with-examples/app/examples/composer-actions/frames/actions/any-embed/route.tsx, templates/next-starter-with-examples/app/examples/composer-actions/frames/actions/create-game/route.tsx
This PR:
- adds missing `imageUrl` to composer action definition
- fixes missing dependencies in debugger's hooks
=> fix: add missing composer action image url

.changeset/tender-foxes-admire.md, docs/pages/reference/render/use-frame.mdx, packages/debugger/app/debugger-page.tsx, packages/debugger/globals.d.ts, packages/render/src/farcaster/attribution.ts, packages/render/src/farcaster/index.ts, packages/render/src/index.tsx, packages/render/src/types.ts, packages/render/src/use-fetch-frame.ts, packages/render/src/use-frame.tsx
Adds attribution for farcaster frame transactions https://www.notion.so/warpcast/Frame-Transactions-Public-9d9f9f4f527249519a41bd8d16165f73#c1c3182208ce4ae4a7ffa72129b9795a
=> feat: farcaster client transaction attribution

.changeset/tall-eggs-float.md, packages/render/src/farcaster/attribution.ts
Correctly `encodePacked` for attribution data encoding.
=> fix(render): encodePacked for attribution

.changeset/curvy-items-kick.md, packages/render/src/identity/anonymous/use-anonymous-identity.tsx
Exports the type `AnonymousSignerInstance` to match `FarcasterSignerInstance` which is exported from `@frames.js/render/identity/farcaster`
=> export `AnonymousSignerInstance` from `@frames.js/render/identity/anonymous`

.changeset/tough-feet-reply.md, packages/frames.js/package.json, yarn.lock
=> chore(frames.js): update @vercel/og dependency

docs/pages/guides/lens.mdx
=> fix: lens docs

docs/pages/guides/apps/best-practices.mdx, docs/vocs.config.tsx
Adds rendering best practices for apps to docs
=> docs: rendering best practices

templates/express/src/entry-server.tsx, templates/hono/src/server.tsx, templates/next/app/frames/frames.ts, templates/next/app/frames/route.tsx
This PR updates the basic frame template to be simpler and reflect the suggested structure in next.js.
=> fix: update basic frame template

docs/vocs.config.tsx
Fixed broken CONTRIBUTING.md link in the header dropdown on the index page
The installation failed with this error:
=> fixed broken CONTRIBUTING.md link

.changeset/soft-dragons-stare.md, packages/debugger/app/components/frame-app-debugger.tsx, packages/debugger/app/components/frame-app.tsx
We added a section where it's possible to set the iframe size, with also presets.
=> Feat: Add device size customization
